${CONDA_PREFIX}/bin/python ${DATA_ROOT}/Download/NextPolish/lib/nextpolish2.py -sp -p 6 -g ${REPO_ROOT}/15.nextpolish/03.hifi_polish/input.genome.fasta -b ${REPO_ROOT}/15.nextpolish/03.hifi_polish/input.genome.fasta.blc -i 0 -l ${REPO_ROOT}/15.nextpolish/03.hifi_polish/hifi.sort.bam.list -r hifi -o genome.nextpolish.part000.fasta
${CONDA_PREFIX}/bin/python ${DATA_ROOT}/Download/NextPolish/lib/nextpolish2.py -sp -p 6 -g ${REPO_ROOT}/15.nextpolish/03.hifi_polish/input.genome.fasta -b ${REPO_ROOT}/15.nextpolish/03.hifi_polish/input.genome.fasta.blc -i 1 -l ${REPO_ROOT}/15.nextpolish/03.hifi_polish/hifi.sort.bam.list -r hifi -o genome.nextpolish.part001.fasta
${CONDA_PREFIX}/bin/python ${DATA_ROOT}/Download/NextPolish/lib/nextpolish2.py -sp -p 6 -g ${REPO_ROOT}/15.nextpolish/03.hifi_polish/input.genome.fasta -b ${REPO_ROOT}/15.nextpolish/03.hifi_polish/input.genome.fasta.blc -i 2 -l ${REPO_ROOT}/15.nextpolish/03.hifi_polish/hifi.sort.bam.list -r hifi -o genome.nextpolish.part002.fasta
${CONDA_PREFIX}/bin/python ${DATA_ROOT}/Download/NextPolish/lib/nextpolish2.py -sp -p 6 -g ${REPO_ROOT}/15.nextpolish/03.hifi_polish/input.genome.fasta -b ${REPO_ROOT}/15.nextpolish/03.hifi_polish/input.genome.fasta.blc -i 3 -l ${REPO_ROOT}/15.nextpolish/03.hifi_polish/hifi.sort.bam.list -r hifi -o genome.nextpolish.part003.fasta
${CONDA_PREFIX}/bin/python ${DATA_ROOT}/Download/NextPolish/lib/nextpolish2.py -sp -p 6 -g ${REPO_ROOT}/15.nextpolish/03.hifi_polish/input.genome.fasta -b ${REPO_ROOT}/15.nextpolish/03.hifi_polish/input.genome.fasta.blc -i 4 -l ${REPO_ROOT}/15.nextpolish/03.hifi_polish/hifi.sort.bam.list -r hifi -o genome.nextpolish.part004.fasta
${CONDA_PREFIX}/bin/python ${DATA_ROOT}/Download/NextPolish/lib/nextpolish2.py -sp -p 6 -g ${REPO_ROOT}/15.nextpolish/03.hifi_polish/input.genome.fasta -b ${REPO_ROOT}/15.nextpolish/03.hifi_polish/input.genome.fasta.blc -i 5 -l ${REPO_ROOT}/15.nextpolish/03.hifi_polish/hifi.sort.bam.list -r hifi -o genome.nextpolish.part005.fasta
${CONDA_PREFIX}/bin/python ${DATA_ROOT}/Download/NextPolish/lib/nextpolish2.py -sp -p 6 -g ${REPO_ROOT}/15.nextpolish/03.hifi_polish/input.genome.fasta -b ${REPO_ROOT}/15.nextpolish/03.hifi_polish/input.genome.fasta.blc -i 6 -l ${REPO_ROOT}/15.nextpolish/03.hifi_polish/hifi.sort.bam.list -r hifi -o genome.nextpolish.part006.fasta
${CONDA_PREFIX}/bin/python ${DATA_ROOT}/Download/NextPolish/lib/nextpolish2.py -sp -p 6 -g ${REPO_ROOT}/15.nextpolish/03.hifi_polish/input.genome.fasta -b ${REPO_ROOT}/15.nextpolish/03.hifi_polish/input.genome.fasta.blc -i 7 -l ${REPO_ROOT}/15.nextpolish/03.hifi_polish/hifi.sort.bam.list -r hifi -o genome.nextpolish.part007.fasta

