set -e
true
true
${DATA_ROOT}/Download/SPAdes-4.3.0-Linux/bin/spades-hammer ${REPO_ROOT}/03.spades_assembly/01.illumina_only/corrected/configs/config.info
${CONDA_PREFIX}/bin/python3 ${DATA_ROOT}/Download/SPAdes-4.3.0-Linux/share/spades/spades_pipeline/supplemetary/compress_all.py --input_file ${REPO_ROOT}/03.spades_assembly/01.illumina_only/corrected/corrected.yaml --ext_python_modules_home ${DATA_ROOT}/Download/SPAdes-4.3.0-Linux/share/spades --max_threads 48 --output_dir ${REPO_ROOT}/03.spades_assembly/01.illumina_only/corrected --gzip_output
true
true
${DATA_ROOT}/Download/SPAdes-4.3.0-Linux/bin/spades-core ${REPO_ROOT}/03.spades_assembly/01.illumina_only/K21/configs/config.info ${REPO_ROOT}/03.spades_assembly/01.illumina_only/K21/configs/careful_mode.info
${DATA_ROOT}/Download/SPAdes-4.3.0-Linux/bin/spades-core ${REPO_ROOT}/03.spades_assembly/01.illumina_only/K55/configs/config.info ${REPO_ROOT}/03.spades_assembly/01.illumina_only/K55/configs/careful_mode.info
${CONDA_PREFIX}/bin/python3 ${DATA_ROOT}/Download/SPAdes-4.3.0-Linux/share/spades/spades_pipeline/supplemetary/copy_files.py ${REPO_ROOT}/03.spades_assembly/01.illumina_only/K55/before_rr.fasta ${REPO_ROOT}/03.spades_assembly/01.illumina_only/before_rr.fasta ${REPO_ROOT}/03.spades_assembly/01.illumina_only/K55/assembly_graph_after_simplification.gfa ${REPO_ROOT}/03.spades_assembly/01.illumina_only/assembly_graph_after_simplification.gfa ${REPO_ROOT}/03.spades_assembly/01.illumina_only/K55/final_contigs.fasta ${REPO_ROOT}/03.spades_assembly/01.illumina_only/contigs.fasta ${REPO_ROOT}/03.spades_assembly/01.illumina_only/K55/first_pe_contigs.fasta ${REPO_ROOT}/03.spades_assembly/01.illumina_only/first_pe_contigs.fasta ${REPO_ROOT}/03.spades_assembly/01.illumina_only/K55/strain_graph.gfa ${REPO_ROOT}/03.spades_assembly/01.illumina_only/strain_graph.gfa ${REPO_ROOT}/03.spades_assembly/01.illumina_only/K55/scaffolds.fasta ${REPO_ROOT}/03.spades_assembly/01.illumina_only/scaffolds.fasta ${REPO_ROOT}/03.spades_assembly/01.illumina_only/K55/scaffolds.paths ${REPO_ROOT}/03.spades_assembly/01.illumina_only/scaffolds.paths ${REPO_ROOT}/03.spades_assembly/01.illumina_only/K55/assembly_graph_with_scaffolds.gfa ${REPO_ROOT}/03.spades_assembly/01.illumina_only/assembly_graph_with_scaffolds.gfa ${REPO_ROOT}/03.spades_assembly/01.illumina_only/K55/assembly_graph.fastg ${REPO_ROOT}/03.spades_assembly/01.illumina_only/assembly_graph.fastg ${REPO_ROOT}/03.spades_assembly/01.illumina_only/K55/final_contigs.paths ${REPO_ROOT}/03.spades_assembly/01.illumina_only/contigs.paths
true
true
${CONDA_PREFIX}/bin/python3 ${DATA_ROOT}/Download/SPAdes-4.3.0-Linux/share/spades/spades_pipeline/supplemetary/correction_iteration_script.py --corrected ${REPO_ROOT}/03.spades_assembly/01.illumina_only/contigs.fasta --assembled ${REPO_ROOT}/03.spades_assembly/01.illumina_only/misc/assembled_contigs.fasta --assembly_type contigs --output_dir ${REPO_ROOT}/03.spades_assembly/01.illumina_only --bin_home ${DATA_ROOT}/Download/SPAdes-4.3.0-Linux/bin
${CONDA_PREFIX}/bin/python3 ${DATA_ROOT}/Download/SPAdes-4.3.0-Linux/share/spades/spades_pipeline/supplemetary/correction_iteration_script.py --corrected ${REPO_ROOT}/03.spades_assembly/01.illumina_only/scaffolds.fasta --assembled ${REPO_ROOT}/03.spades_assembly/01.illumina_only/misc/assembled_scaffolds.fasta --assembly_type scaffolds --output_dir ${REPO_ROOT}/03.spades_assembly/01.illumina_only --bin_home ${DATA_ROOT}/Download/SPAdes-4.3.0-Linux/bin
true
${CONDA_PREFIX}/bin/python3 ${DATA_ROOT}/Download/SPAdes-4.3.0-Linux/share/spades/spades_pipeline/supplemetary/breaking_scaffolds_script.py --result_scaffolds_filename ${REPO_ROOT}/03.spades_assembly/01.illumina_only/scaffolds.fasta --misc_dir ${REPO_ROOT}/03.spades_assembly/01.illumina_only/misc --threshold_for_breaking_scaffolds 3
true
