${DATA_ROOT}/Download/NextPolish/bin/bwa mem -p  -t 6 ${REPO_ROOT}/15.nextpolish/07.kmer_count/input.genome.fasta.sgs ${REPO_ROOT}/15.nextpolish/input.sgspart.000.fastq.gz|${DATA_ROOT}/Download/NextPolish/bin/samtools view --threads 5 -F 0x4 -b - |${DATA_ROOT}/Download/NextPolish/bin/samtools fixmate -m --threads 5  - - |${DATA_ROOT}/Download/NextPolish/bin/samtools sort - -m 2g --threads 5 -o sgs.part000.sort.bam
${DATA_ROOT}/Download/NextPolish/bin/bwa mem -p  -t 6 ${REPO_ROOT}/15.nextpolish/07.kmer_count/input.genome.fasta.sgs ${REPO_ROOT}/15.nextpolish/input.sgspart.001.fastq.gz|${DATA_ROOT}/Download/NextPolish/bin/samtools view --threads 5 -F 0x4 -b - |${DATA_ROOT}/Download/NextPolish/bin/samtools fixmate -m --threads 5  - - |${DATA_ROOT}/Download/NextPolish/bin/samtools sort - -m 2g --threads 5 -o sgs.part001.sort.bam
${DATA_ROOT}/Download/NextPolish/bin/bwa mem -p  -t 6 ${REPO_ROOT}/15.nextpolish/07.kmer_count/input.genome.fasta.sgs ${REPO_ROOT}/15.nextpolish/input.sgspart.002.fastq.gz|${DATA_ROOT}/Download/NextPolish/bin/samtools view --threads 5 -F 0x4 -b - |${DATA_ROOT}/Download/NextPolish/bin/samtools fixmate -m --threads 5  - - |${DATA_ROOT}/Download/NextPolish/bin/samtools sort - -m 2g --threads 5 -o sgs.part002.sort.bam
${DATA_ROOT}/Download/NextPolish/bin/bwa mem -p  -t 6 ${REPO_ROOT}/15.nextpolish/07.kmer_count/input.genome.fasta.sgs ${REPO_ROOT}/15.nextpolish/input.sgspart.003.fastq.gz|${DATA_ROOT}/Download/NextPolish/bin/samtools view --threads 5 -F 0x4 -b - |${DATA_ROOT}/Download/NextPolish/bin/samtools fixmate -m --threads 5  - - |${DATA_ROOT}/Download/NextPolish/bin/samtools sort - -m 2g --threads 5 -o sgs.part003.sort.bam
${DATA_ROOT}/Download/NextPolish/bin/bwa mem -p  -t 6 ${REPO_ROOT}/15.nextpolish/07.kmer_count/input.genome.fasta.sgs ${REPO_ROOT}/15.nextpolish/input.sgspart.004.fastq.gz|${DATA_ROOT}/Download/NextPolish/bin/samtools view --threads 5 -F 0x4 -b - |${DATA_ROOT}/Download/NextPolish/bin/samtools fixmate -m --threads 5  - - |${DATA_ROOT}/Download/NextPolish/bin/samtools sort - -m 2g --threads 5 -o sgs.part004.sort.bam
${DATA_ROOT}/Download/NextPolish/bin/bwa mem -p  -t 6 ${REPO_ROOT}/15.nextpolish/07.kmer_count/input.genome.fasta.sgs ${REPO_ROOT}/15.nextpolish/input.sgspart.005.fastq.gz|${DATA_ROOT}/Download/NextPolish/bin/samtools view --threads 5 -F 0x4 -b - |${DATA_ROOT}/Download/NextPolish/bin/samtools fixmate -m --threads 5  - - |${DATA_ROOT}/Download/NextPolish/bin/samtools sort - -m 2g --threads 5 -o sgs.part005.sort.bam
${DATA_ROOT}/Download/NextPolish/bin/bwa mem -p  -t 6 ${REPO_ROOT}/15.nextpolish/07.kmer_count/input.genome.fasta.sgs ${REPO_ROOT}/15.nextpolish/input.sgspart.006.fastq.gz|${DATA_ROOT}/Download/NextPolish/bin/samtools view --threads 5 -F 0x4 -b - |${DATA_ROOT}/Download/NextPolish/bin/samtools fixmate -m --threads 5  - - |${DATA_ROOT}/Download/NextPolish/bin/samtools sort - -m 2g --threads 5 -o sgs.part006.sort.bam
${DATA_ROOT}/Download/NextPolish/bin/bwa mem -p  -t 6 ${REPO_ROOT}/15.nextpolish/07.kmer_count/input.genome.fasta.sgs ${REPO_ROOT}/15.nextpolish/input.sgspart.007.fastq.gz|${DATA_ROOT}/Download/NextPolish/bin/samtools view --threads 5 -F 0x4 -b - |${DATA_ROOT}/Download/NextPolish/bin/samtools fixmate -m --threads 5  - - |${DATA_ROOT}/Download/NextPolish/bin/samtools sort - -m 2g --threads 5 -o sgs.part007.sort.bam

