${CONDA_PREFIX}/bin/python ${DATA_ROOT}/Download/NextPolish/lib/nextpolish1.py -p 6 -g ${REPO_ROOT}/15.nextpolish/07.kmer_count/input.genome.fasta -b ${REPO_ROOT}/15.nextpolish/07.kmer_count/input.genome.fasta.blc -i 0 -t 2 -s ${REPO_ROOT}/15.nextpolish/07.kmer_count/sgs.sort.bam -l ${REPO_ROOT}/15.nextpolish/07.kmer_count/lgs.sort.bam -o genome.nextpolish.part000.fasta
${CONDA_PREFIX}/bin/python ${DATA_ROOT}/Download/NextPolish/lib/nextpolish1.py -p 6 -g ${REPO_ROOT}/15.nextpolish/07.kmer_count/input.genome.fasta -b ${REPO_ROOT}/15.nextpolish/07.kmer_count/input.genome.fasta.blc -i 1 -t 2 -s ${REPO_ROOT}/15.nextpolish/07.kmer_count/sgs.sort.bam -l ${REPO_ROOT}/15.nextpolish/07.kmer_count/lgs.sort.bam -o genome.nextpolish.part001.fasta
${CONDA_PREFIX}/bin/python ${DATA_ROOT}/Download/NextPolish/lib/nextpolish1.py -p 6 -g ${REPO_ROOT}/15.nextpolish/07.kmer_count/input.genome.fasta -b ${REPO_ROOT}/15.nextpolish/07.kmer_count/input.genome.fasta.blc -i 2 -t 2 -s ${REPO_ROOT}/15.nextpolish/07.kmer_count/sgs.sort.bam -l ${REPO_ROOT}/15.nextpolish/07.kmer_count/lgs.sort.bam -o genome.nextpolish.part002.fasta
${CONDA_PREFIX}/bin/python ${DATA_ROOT}/Download/NextPolish/lib/nextpolish1.py -p 6 -g ${REPO_ROOT}/15.nextpolish/07.kmer_count/input.genome.fasta -b ${REPO_ROOT}/15.nextpolish/07.kmer_count/input.genome.fasta.blc -i 3 -t 2 -s ${REPO_ROOT}/15.nextpolish/07.kmer_count/sgs.sort.bam -l ${REPO_ROOT}/15.nextpolish/07.kmer_count/lgs.sort.bam -o genome.nextpolish.part003.fasta
${CONDA_PREFIX}/bin/python ${DATA_ROOT}/Download/NextPolish/lib/nextpolish1.py -p 6 -g ${REPO_ROOT}/15.nextpolish/07.kmer_count/input.genome.fasta -b ${REPO_ROOT}/15.nextpolish/07.kmer_count/input.genome.fasta.blc -i 4 -t 2 -s ${REPO_ROOT}/15.nextpolish/07.kmer_count/sgs.sort.bam -l ${REPO_ROOT}/15.nextpolish/07.kmer_count/lgs.sort.bam -o genome.nextpolish.part004.fasta
${CONDA_PREFIX}/bin/python ${DATA_ROOT}/Download/NextPolish/lib/nextpolish1.py -p 6 -g ${REPO_ROOT}/15.nextpolish/07.kmer_count/input.genome.fasta -b ${REPO_ROOT}/15.nextpolish/07.kmer_count/input.genome.fasta.blc -i 5 -t 2 -s ${REPO_ROOT}/15.nextpolish/07.kmer_count/sgs.sort.bam -l ${REPO_ROOT}/15.nextpolish/07.kmer_count/lgs.sort.bam -o genome.nextpolish.part005.fasta
${CONDA_PREFIX}/bin/python ${DATA_ROOT}/Download/NextPolish/lib/nextpolish1.py -p 6 -g ${REPO_ROOT}/15.nextpolish/07.kmer_count/input.genome.fasta -b ${REPO_ROOT}/15.nextpolish/07.kmer_count/input.genome.fasta.blc -i 6 -t 2 -s ${REPO_ROOT}/15.nextpolish/07.kmer_count/sgs.sort.bam -l ${REPO_ROOT}/15.nextpolish/07.kmer_count/lgs.sort.bam -o genome.nextpolish.part006.fasta
${CONDA_PREFIX}/bin/python ${DATA_ROOT}/Download/NextPolish/lib/nextpolish1.py -p 6 -g ${REPO_ROOT}/15.nextpolish/07.kmer_count/input.genome.fasta -b ${REPO_ROOT}/15.nextpolish/07.kmer_count/input.genome.fasta.blc -i 7 -t 2 -s ${REPO_ROOT}/15.nextpolish/07.kmer_count/sgs.sort.bam -l ${REPO_ROOT}/15.nextpolish/07.kmer_count/lgs.sort.bam -o genome.nextpolish.part007.fasta

