set -e
true
true
${DATA_ROOT}/Download/SPAdes-4.3.0-Linux/bin/spades-hammer ${REPO_ROOT}/03.spades_assembly/02.illumina_hifi/corrected/configs/config.info
${CONDA_PREFIX}/bin/python3 ${DATA_ROOT}/Download/SPAdes-4.3.0-Linux/share/spades/spades_pipeline/supplemetary/compress_all.py --input_file ${REPO_ROOT}/03.spades_assembly/02.illumina_hifi/corrected/corrected.yaml --ext_python_modules_home ${DATA_ROOT}/Download/SPAdes-4.3.0-Linux/share/spades --max_threads 48 --output_dir ${REPO_ROOT}/03.spades_assembly/02.illumina_hifi/corrected --not_used_yaml_file ${REPO_ROOT}/03.spades_assembly/02.illumina_hifi/corrected/dont_correct.yaml --gzip_output
true
true
${DATA_ROOT}/Download/SPAdes-4.3.0-Linux/bin/spades-core ${REPO_ROOT}/03.spades_assembly/02.illumina_hifi/K55/configs/config.info ${REPO_ROOT}/03.spades_assembly/02.illumina_hifi/K55/configs/careful_mode.info
${DATA_ROOT}/Download/SPAdes-4.3.0-Linux/bin/spades-core ${REPO_ROOT}/03.spades_assembly/02.illumina_hifi/K127/configs/config.info ${REPO_ROOT}/03.spades_assembly/02.illumina_hifi/K127/configs/careful_mode.info
${CONDA_PREFIX}/bin/python3 ${DATA_ROOT}/Download/SPAdes-4.3.0-Linux/share/spades/spades_pipeline/supplemetary/copy_files.py ${REPO_ROOT}/03.spades_assembly/02.illumina_hifi/K127/before_rr.fasta ${REPO_ROOT}/03.spades_assembly/02.illumina_hifi/before_rr.fasta ${REPO_ROOT}/03.spades_assembly/02.illumina_hifi/K127/assembly_graph_after_simplification.gfa ${REPO_ROOT}/03.spades_assembly/02.illumina_hifi/assembly_graph_after_simplification.gfa ${REPO_ROOT}/03.spades_assembly/02.illumina_hifi/K127/final_contigs.fasta ${REPO_ROOT}/03.spades_assembly/02.illumina_hifi/contigs.fasta ${REPO_ROOT}/03.spades_assembly/02.illumina_hifi/K127/first_pe_contigs.fasta ${REPO_ROOT}/03.spades_assembly/02.illumina_hifi/first_pe_contigs.fasta ${REPO_ROOT}/03.spades_assembly/02.illumina_hifi/K127/strain_graph.gfa ${REPO_ROOT}/03.spades_assembly/02.illumina_hifi/strain_graph.gfa ${REPO_ROOT}/03.spades_assembly/02.illumina_hifi/K127/scaffolds.fasta ${REPO_ROOT}/03.spades_assembly/02.illumina_hifi/scaffolds.fasta ${REPO_ROOT}/03.spades_assembly/02.illumina_hifi/K127/scaffolds.paths ${REPO_ROOT}/03.spades_assembly/02.illumina_hifi/scaffolds.paths ${REPO_ROOT}/03.spades_assembly/02.illumina_hifi/K127/assembly_graph_with_scaffolds.gfa ${REPO_ROOT}/03.spades_assembly/02.illumina_hifi/assembly_graph_with_scaffolds.gfa ${REPO_ROOT}/03.spades_assembly/02.illumina_hifi/K127/assembly_graph.fastg ${REPO_ROOT}/03.spades_assembly/02.illumina_hifi/assembly_graph.fastg ${REPO_ROOT}/03.spades_assembly/02.illumina_hifi/K127/final_contigs.paths ${REPO_ROOT}/03.spades_assembly/02.illumina_hifi/contigs.paths
true
true
${CONDA_PREFIX}/bin/python3 ${DATA_ROOT}/Download/SPAdes-4.3.0-Linux/share/spades/spades_pipeline/supplemetary/correction_iteration_script.py --corrected ${REPO_ROOT}/03.spades_assembly/02.illumina_hifi/contigs.fasta --assembled ${REPO_ROOT}/03.spades_assembly/02.illumina_hifi/misc/assembled_contigs.fasta --assembly_type contigs --output_dir ${REPO_ROOT}/03.spades_assembly/02.illumina_hifi --bin_home ${DATA_ROOT}/Download/SPAdes-4.3.0-Linux/bin
${CONDA_PREFIX}/bin/python3 ${DATA_ROOT}/Download/SPAdes-4.3.0-Linux/share/spades/spades_pipeline/supplemetary/correction_iteration_script.py --corrected ${REPO_ROOT}/03.spades_assembly/02.illumina_hifi/scaffolds.fasta --assembled ${REPO_ROOT}/03.spades_assembly/02.illumina_hifi/misc/assembled_scaffolds.fasta --assembly_type scaffolds --output_dir ${REPO_ROOT}/03.spades_assembly/02.illumina_hifi --bin_home ${DATA_ROOT}/Download/SPAdes-4.3.0-Linux/bin
true
${CONDA_PREFIX}/bin/python3 ${DATA_ROOT}/Download/SPAdes-4.3.0-Linux/share/spades/spades_pipeline/supplemetary/breaking_scaffolds_script.py --result_scaffolds_filename ${REPO_ROOT}/03.spades_assembly/02.illumina_hifi/scaffolds.fasta --misc_dir ${REPO_ROOT}/03.spades_assembly/02.illumina_hifi/misc --threshold_for_breaking_scaffolds 3
true
