${DATA_ROOT}/Download/NextPolish/bin/minimap2 --split-prefix tmp -a -x map-ont -t 6 ${REPO_ROOT}/15.nextpolish/01.lgs_polish/input.genome.fasta ${REPO_ROOT}/15.nextpolish/input.lgspart.000.fasta.gz|${DATA_ROOT}/Download/NextPolish/bin/samtools view --threads 5 -F 0x4 -b - |${DATA_ROOT}/Download/NextPolish/bin/samtools sort - -m 2g --threads 5 -o lgs.part000.sort.bam
${DATA_ROOT}/Download/NextPolish/bin/minimap2 --split-prefix tmp -a -x map-ont -t 6 ${REPO_ROOT}/15.nextpolish/01.lgs_polish/input.genome.fasta ${REPO_ROOT}/15.nextpolish/input.lgspart.001.fasta.gz|${DATA_ROOT}/Download/NextPolish/bin/samtools view --threads 5 -F 0x4 -b - |${DATA_ROOT}/Download/NextPolish/bin/samtools sort - -m 2g --threads 5 -o lgs.part001.sort.bam
${DATA_ROOT}/Download/NextPolish/bin/minimap2 --split-prefix tmp -a -x map-ont -t 6 ${REPO_ROOT}/15.nextpolish/01.lgs_polish/input.genome.fasta ${REPO_ROOT}/15.nextpolish/input.lgspart.002.fasta.gz|${DATA_ROOT}/Download/NextPolish/bin/samtools view --threads 5 -F 0x4 -b - |${DATA_ROOT}/Download/NextPolish/bin/samtools sort - -m 2g --threads 5 -o lgs.part002.sort.bam
${DATA_ROOT}/Download/NextPolish/bin/minimap2 --split-prefix tmp -a -x map-ont -t 6 ${REPO_ROOT}/15.nextpolish/01.lgs_polish/input.genome.fasta ${REPO_ROOT}/15.nextpolish/input.lgspart.003.fasta.gz|${DATA_ROOT}/Download/NextPolish/bin/samtools view --threads 5 -F 0x4 -b - |${DATA_ROOT}/Download/NextPolish/bin/samtools sort - -m 2g --threads 5 -o lgs.part003.sort.bam
${DATA_ROOT}/Download/NextPolish/bin/minimap2 --split-prefix tmp -a -x map-ont -t 6 ${REPO_ROOT}/15.nextpolish/01.lgs_polish/input.genome.fasta ${REPO_ROOT}/15.nextpolish/input.lgspart.004.fasta.gz|${DATA_ROOT}/Download/NextPolish/bin/samtools view --threads 5 -F 0x4 -b - |${DATA_ROOT}/Download/NextPolish/bin/samtools sort - -m 2g --threads 5 -o lgs.part004.sort.bam
${DATA_ROOT}/Download/NextPolish/bin/minimap2 --split-prefix tmp -a -x map-ont -t 6 ${REPO_ROOT}/15.nextpolish/01.lgs_polish/input.genome.fasta ${REPO_ROOT}/15.nextpolish/input.lgspart.005.fasta.gz|${DATA_ROOT}/Download/NextPolish/bin/samtools view --threads 5 -F 0x4 -b - |${DATA_ROOT}/Download/NextPolish/bin/samtools sort - -m 2g --threads 5 -o lgs.part005.sort.bam
${DATA_ROOT}/Download/NextPolish/bin/minimap2 --split-prefix tmp -a -x map-ont -t 6 ${REPO_ROOT}/15.nextpolish/01.lgs_polish/input.genome.fasta ${REPO_ROOT}/15.nextpolish/input.lgspart.006.fasta.gz|${DATA_ROOT}/Download/NextPolish/bin/samtools view --threads 5 -F 0x4 -b - |${DATA_ROOT}/Download/NextPolish/bin/samtools sort - -m 2g --threads 5 -o lgs.part006.sort.bam
${DATA_ROOT}/Download/NextPolish/bin/minimap2 --split-prefix tmp -a -x map-ont -t 6 ${REPO_ROOT}/15.nextpolish/01.lgs_polish/input.genome.fasta ${REPO_ROOT}/15.nextpolish/input.lgspart.007.fasta.gz|${DATA_ROOT}/Download/NextPolish/bin/samtools view --threads 5 -F 0x4 -b - |${DATA_ROOT}/Download/NextPolish/bin/samtools sort - -m 2g --threads 5 -o lgs.part007.sort.bam

