${DATA_ROOT}/Download/NextPolish/bin/minimap2 --split-prefix tmp -a -x map-pb -t 6 ${REPO_ROOT}/15.nextpolish/02.hifi_polish/input.genome.fasta ${REPO_ROOT}/15.nextpolish/input.hifipart.000.fasta.gz|${DATA_ROOT}/Download/NextPolish/bin/samtools view --threads 5 -F 0x4 -b - |${DATA_ROOT}/Download/NextPolish/bin/samtools sort - -m 2g --threads 5 -o hifi.part000.sort.bam
${DATA_ROOT}/Download/NextPolish/bin/minimap2 --split-prefix tmp -a -x map-pb -t 6 ${REPO_ROOT}/15.nextpolish/02.hifi_polish/input.genome.fasta ${REPO_ROOT}/15.nextpolish/input.hifipart.001.fasta.gz|${DATA_ROOT}/Download/NextPolish/bin/samtools view --threads 5 -F 0x4 -b - |${DATA_ROOT}/Download/NextPolish/bin/samtools sort - -m 2g --threads 5 -o hifi.part001.sort.bam
${DATA_ROOT}/Download/NextPolish/bin/minimap2 --split-prefix tmp -a -x map-pb -t 6 ${REPO_ROOT}/15.nextpolish/02.hifi_polish/input.genome.fasta ${REPO_ROOT}/15.nextpolish/input.hifipart.002.fasta.gz|${DATA_ROOT}/Download/NextPolish/bin/samtools view --threads 5 -F 0x4 -b - |${DATA_ROOT}/Download/NextPolish/bin/samtools sort - -m 2g --threads 5 -o hifi.part002.sort.bam
${DATA_ROOT}/Download/NextPolish/bin/minimap2 --split-prefix tmp -a -x map-pb -t 6 ${REPO_ROOT}/15.nextpolish/02.hifi_polish/input.genome.fasta ${REPO_ROOT}/15.nextpolish/input.hifipart.003.fasta.gz|${DATA_ROOT}/Download/NextPolish/bin/samtools view --threads 5 -F 0x4 -b - |${DATA_ROOT}/Download/NextPolish/bin/samtools sort - -m 2g --threads 5 -o hifi.part003.sort.bam
${DATA_ROOT}/Download/NextPolish/bin/minimap2 --split-prefix tmp -a -x map-pb -t 6 ${REPO_ROOT}/15.nextpolish/02.hifi_polish/input.genome.fasta ${REPO_ROOT}/15.nextpolish/input.hifipart.004.fasta.gz|${DATA_ROOT}/Download/NextPolish/bin/samtools view --threads 5 -F 0x4 -b - |${DATA_ROOT}/Download/NextPolish/bin/samtools sort - -m 2g --threads 5 -o hifi.part004.sort.bam
${DATA_ROOT}/Download/NextPolish/bin/minimap2 --split-prefix tmp -a -x map-pb -t 6 ${REPO_ROOT}/15.nextpolish/02.hifi_polish/input.genome.fasta ${REPO_ROOT}/15.nextpolish/input.hifipart.005.fasta.gz|${DATA_ROOT}/Download/NextPolish/bin/samtools view --threads 5 -F 0x4 -b - |${DATA_ROOT}/Download/NextPolish/bin/samtools sort - -m 2g --threads 5 -o hifi.part005.sort.bam
${DATA_ROOT}/Download/NextPolish/bin/minimap2 --split-prefix tmp -a -x map-pb -t 6 ${REPO_ROOT}/15.nextpolish/02.hifi_polish/input.genome.fasta ${REPO_ROOT}/15.nextpolish/input.hifipart.006.fasta.gz|${DATA_ROOT}/Download/NextPolish/bin/samtools view --threads 5 -F 0x4 -b - |${DATA_ROOT}/Download/NextPolish/bin/samtools sort - -m 2g --threads 5 -o hifi.part006.sort.bam
${DATA_ROOT}/Download/NextPolish/bin/minimap2 --split-prefix tmp -a -x map-pb -t 6 ${REPO_ROOT}/15.nextpolish/02.hifi_polish/input.genome.fasta ${REPO_ROOT}/15.nextpolish/input.hifipart.007.fasta.gz|${DATA_ROOT}/Download/NextPolish/bin/samtools view --threads 5 -F 0x4 -b - |${DATA_ROOT}/Download/NextPolish/bin/samtools sort - -m 2g --threads 5 -o hifi.part007.sort.bam

